name: cortado_env
channels:
  - conda-forge
dependencies:
  - conda-forge::python
  - numpy
  - coffea=2025.3.0
  - ndcctools
  - conda-pack
  - dill
  - xrootd
  - git
  - pyyaml
  - fsspec-xrootd
  - conda-forge::dask-awkward=2025.5.0
